spring.application.name=Produtos

spring.datasource.url=jdbc:postgresql://localhost:5432/ProdutosE_Commerce
spring.datasource.username=postgres
spring.datasource.password=Vini-sousa-123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgresPlusDialect

usuario.url=localhost:8085/auth

server.port=8086